from typing import List

from interactions.client.bot import Client

class DummyClient(Client):
    def __init__(self, token: str, **kwargs) -> None: ...
    async def _ready(self) -> None: ...

class MethodReplacer(Client):
    _clients: List[DummyClient] = []
    def __init__(self) -> None: ...
    def start(self) -> None: ...
    async def _login(self) -> None: ...
    async def __login(self) -> None: ...
    async def __ready(self) -> None: ...
    async def _ready(self) -> None: ...
